CREATE SCHEMA IF NOT EXISTS metadata;
CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;

COMMENT ON SCHEMA metadata IS 'Pipeline run metadata, data quality reports, and data contracts.';
COMMENT ON SCHEMA bronze IS 'Raw-preserved lakehouse table representations.';
COMMENT ON SCHEMA silver IS 'Clean staged lakehouse table representations.';
COMMENT ON SCHEMA gold IS 'Curated facts, dimensions, OBTs, and feature tables.';

CREATE TABLE IF NOT EXISTS metadata.pipeline_runs (
    pipeline_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name TEXT NOT NULL,
    run_id TEXT NOT NULL UNIQUE,
    layer_name TEXT NOT NULL CHECK (layer_name IN ('bronze', 'silver', 'gold', 'streaming')),
    status TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed', 'skipped')),
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    source_system TEXT,
    source_path TEXT,
    target_table TEXT,
    row_count BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS metadata.data_quality_reports (
    quality_report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT REFERENCES metadata.pipeline_runs (pipeline_run_id),
    layer_name TEXT NOT NULL CHECK (layer_name IN ('bronze', 'silver', 'gold', 'streaming')),
    table_name TEXT NOT NULL,
    report_path TEXT,
    row_count BIGINT,
    issue_count BIGINT,
    status TEXT NOT NULL CHECK (status IN ('passed', 'warning', 'failed')),
    report_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS metadata.data_contracts (
    data_contract_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name TEXT NOT NULL,
    table_name TEXT NOT NULL,
    contract_version TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    contract_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (schema_name, table_name, contract_version)
);

CREATE TABLE IF NOT EXISTS bronze.raw_transaction_ingest_runs (
    ingest_run_id TEXT PRIMARY KEY,
    source_system TEXT NOT NULL,
    source_dataset TEXT NOT NULL,
    source_path TEXT NOT NULL,
    manifest_path TEXT,
    ingest_date DATE NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    row_count BIGINT NOT NULL DEFAULT 0,
    source_file_count BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed')),
    summary_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bronze.raw_transactions (
    bronze_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id TEXT,
    account_id TEXT,
    customer_id TEXT,
    merchant_id TEXT,
    merchant_category TEXT,
    amount TEXT,
    currency TEXT,
    city TEXT,
    channel TEXT,
    transaction_status TEXT,
    is_fraud TEXT,
    event_timestamp TEXT,
    created_ts TEXT,
    device_id TEXT,
    ip_address TEXT,
    authentication_method TEXT,
    risk_signal_version TEXT,
    _source_system TEXT NOT NULL,
    _source_dataset TEXT NOT NULL,
    _source_file_path TEXT NOT NULL,
    _source_file_name TEXT NOT NULL,
    _source_row_number BIGINT,
    _source_manifest_path TEXT,
    _source_manifest_created_at TEXT,
    _ingest_run_id TEXT NOT NULL REFERENCES bronze.raw_transaction_ingest_runs (ingest_run_id),
    _ingested_at TIMESTAMPTZ NOT NULL,
    _raw_record_hash TEXT NOT NULL,
    _corrupt_record TEXT,
    ingest_date DATE NOT NULL,
    schema_version TEXT NOT NULL CHECK (schema_version IN ('v1', 'v2')),
    transaction_date DATE NOT NULL,
    _loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_raw_transactions_transaction_id
    ON bronze.raw_transactions (transaction_id);

CREATE INDEX IF NOT EXISTS ix_raw_transactions_partitions
    ON bronze.raw_transactions (ingest_date, schema_version, transaction_date);

CREATE INDEX IF NOT EXISTS ix_raw_transactions_source_file
    ON bronze.raw_transactions (_source_file_path);

CREATE TABLE IF NOT EXISTS silver.stg_transactions (
    transaction_id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    customer_id TEXT NOT NULL,
    merchant_id TEXT,
    merchant_category TEXT,
    amount NUMERIC(18, 2) NOT NULL CHECK (amount >= 0),
    currency TEXT NOT NULL,
    city TEXT,
    channel TEXT NOT NULL,
    transaction_status TEXT NOT NULL,
    is_fraud BOOLEAN NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    event_date DATE NOT NULL,
    source_created_at TIMESTAMPTZ,
    arrival_delay_minutes DOUBLE PRECISION,
    device_id TEXT,
    ip_address TEXT,
    authentication_method TEXT,
    risk_signal_version TEXT,
    quality_status TEXT NOT NULL CHECK (quality_status IN ('valid', 'warning')),
    quality_issue_codes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    duplicate_record_count INTEGER NOT NULL DEFAULT 1 CHECK (duplicate_record_count >= 1),
    dedup_rank INTEGER NOT NULL DEFAULT 1 CHECK (dedup_rank >= 1),
    _bronze_ingest_run_id TEXT,
    _bronze_source_file_path TEXT,
    _bronze_source_row_number BIGINT,
    _bronze_raw_record_hash TEXT NOT NULL,
    _silver_processed_at TIMESTAMPTZ NOT NULL,
    _loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_stg_transactions_event_date
    ON silver.stg_transactions (event_date);

CREATE INDEX IF NOT EXISTS ix_stg_transactions_customer_event_time
    ON silver.stg_transactions (customer_id, event_time);

CREATE INDEX IF NOT EXISTS ix_stg_transactions_merchant_event_time
    ON silver.stg_transactions (merchant_id, event_time);

CREATE TABLE IF NOT EXISTS silver.stg_transaction_quality_issues (
    quality_evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id TEXT,
    account_id TEXT,
    customer_id TEXT,
    merchant_id TEXT,
    merchant_category TEXT,
    amount NUMERIC(18, 2),
    currency TEXT,
    city TEXT,
    channel TEXT,
    transaction_status TEXT,
    is_fraud BOOLEAN,
    event_time TIMESTAMPTZ,
    event_date DATE,
    source_created_at TIMESTAMPTZ,
    arrival_delay_minutes DOUBLE PRECISION,
    device_id TEXT,
    ip_address TEXT,
    authentication_method TEXT,
    risk_signal_version TEXT,
    quality_status TEXT NOT NULL CHECK (quality_status IN ('valid', 'warning', 'quarantined')),
    quality_issue_codes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    duplicate_record_count INTEGER,
    dedup_rank INTEGER,
    _bronze_ingest_run_id TEXT,
    _bronze_source_file_path TEXT,
    _bronze_source_row_number BIGINT,
    _bronze_raw_record_hash TEXT,
    _silver_processed_at TIMESTAMPTZ,
    _silver_record_action TEXT NOT NULL CHECK (
        _silver_record_action IN ('selected', 'duplicate_rejected', 'quarantined')
    ),
    _silver_quality_reported_at TIMESTAMPTZ NOT NULL,
    _loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_stg_quality_issues_transaction_id
    ON silver.stg_transaction_quality_issues (transaction_id);

CREATE INDEX IF NOT EXISTS ix_stg_quality_issues_status_action
    ON silver.stg_transaction_quality_issues (quality_status, _silver_record_action);

CREATE TABLE IF NOT EXISTS gold.dim_date (
    date_key INTEGER PRIMARY KEY,
    event_date DATE NOT NULL UNIQUE,
    year INTEGER NOT NULL,
    quarter INTEGER NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    month_name TEXT NOT NULL,
    day_of_month INTEGER NOT NULL CHECK (day_of_month BETWEEN 1 AND 31),
    day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    day_name TEXT NOT NULL,
    week_start_date DATE NOT NULL,
    month_start_date DATE NOT NULL,
    is_weekend BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS gold.dim_city (
    city_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city TEXT NOT NULL,
    state_code TEXT,
    country_code TEXT NOT NULL DEFAULT 'US',
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (city, country_code)
);

CREATE TABLE IF NOT EXISTS gold.dim_channel (
    channel_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel TEXT NOT NULL UNIQUE,
    channel_group TEXT NOT NULL,
    is_digital BOOLEAN NOT NULL,
    is_card_present BOOLEAN NOT NULL,
    description TEXT NOT NULL,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gold.dim_quality_issue (
    quality_issue_code TEXT PRIMARY KEY,
    severity TEXT NOT NULL CHECK (severity IN ('warning', 'quarantine')),
    layer_origin TEXT NOT NULL CHECK (layer_origin IN ('bronze', 'silver', 'gold')),
    description TEXT NOT NULL,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gold.dim_merchant_category (
    merchant_category_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_category TEXT NOT NULL UNIQUE,
    category_group TEXT,
    description TEXT,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gold.dim_customer (
    customer_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    first_event_date DATE NOT NULL,
    last_event_date DATE NOT NULL,
    primary_city_key BIGINT REFERENCES gold.dim_city (city_key),
    primary_city TEXT,
    account_count BIGINT NOT NULL DEFAULT 0 CHECK (account_count >= 0),
    lifetime_transaction_count BIGINT NOT NULL DEFAULT 0 CHECK (lifetime_transaction_count >= 0),
    lifetime_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (lifetime_amount >= 0),
    average_transaction_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (average_transaction_amount >= 0),
    fraud_transaction_count BIGINT NOT NULL DEFAULT 0 CHECK (fraud_transaction_count >= 0),
    fraud_rate DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (fraud_rate >= 0 AND fraud_rate <= 1),
    warning_transaction_count BIGINT NOT NULL DEFAULT 0 CHECK (warning_transaction_count >= 0),
    valid_from_ts TIMESTAMPTZ NOT NULL,
    valid_to_ts TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT true,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (valid_to_ts IS NULL OR valid_to_ts > valid_from_ts)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_customer_current
    ON gold.dim_customer (customer_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS ix_dim_customer_natural_history
    ON gold.dim_customer (customer_id, valid_from_ts, valid_to_ts);

CREATE TABLE IF NOT EXISTS gold.dim_account (
    account_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id TEXT NOT NULL,
    customer_key BIGINT NOT NULL REFERENCES gold.dim_customer (customer_key),
    customer_id TEXT NOT NULL,
    customer_count BIGINT NOT NULL DEFAULT 1 CHECK (customer_count >= 1),
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    transaction_count BIGINT NOT NULL DEFAULT 0 CHECK (transaction_count >= 0),
    lifetime_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (lifetime_amount >= 0),
    distinct_merchant_count BIGINT NOT NULL DEFAULT 0 CHECK (distinct_merchant_count >= 0),
    fraud_transaction_count BIGINT NOT NULL DEFAULT 0 CHECK (fraud_transaction_count >= 0),
    warning_transaction_count BIGINT NOT NULL DEFAULT 0 CHECK (warning_transaction_count >= 0),
    valid_from_ts TIMESTAMPTZ NOT NULL,
    valid_to_ts TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT true,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (valid_to_ts IS NULL OR valid_to_ts > valid_from_ts)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_account_current
    ON gold.dim_account (account_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS ix_dim_account_customer_key
    ON gold.dim_account (customer_key);

CREATE TABLE IF NOT EXISTS gold.dim_merchant (
    merchant_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_dim_id TEXT NOT NULL,
    merchant_id TEXT,
    merchant_category_key BIGINT REFERENCES gold.dim_merchant_category (merchant_category_key),
    merchant_category TEXT,
    primary_city_key BIGINT REFERENCES gold.dim_city (city_key),
    primary_city TEXT,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    transaction_count BIGINT NOT NULL DEFAULT 0 CHECK (transaction_count >= 0),
    distinct_customer_count BIGINT NOT NULL DEFAULT 0 CHECK (distinct_customer_count >= 0),
    lifetime_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (lifetime_amount >= 0),
    average_transaction_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (average_transaction_amount >= 0),
    fraud_transaction_count BIGINT NOT NULL DEFAULT 0 CHECK (fraud_transaction_count >= 0),
    fraud_rate DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (fraud_rate >= 0 AND fraud_rate <= 1),
    warning_transaction_count BIGINT NOT NULL DEFAULT 0 CHECK (warning_transaction_count >= 0),
    valid_from_ts TIMESTAMPTZ NOT NULL,
    valid_to_ts TIMESTAMPTZ,
    is_current BOOLEAN NOT NULL DEFAULT true,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (valid_to_ts IS NULL OR valid_to_ts > valid_from_ts)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_merchant_current
    ON gold.dim_merchant (merchant_dim_id)
    WHERE is_current;

CREATE INDEX IF NOT EXISTS ix_dim_merchant_category_key
    ON gold.dim_merchant (merchant_category_key);

CREATE TABLE IF NOT EXISTS gold.fact_transactions (
    transaction_id TEXT PRIMARY KEY,
    event_time TIMESTAMPTZ NOT NULL,
    event_date DATE NOT NULL,
    date_key INTEGER NOT NULL REFERENCES gold.dim_date (date_key),
    customer_key BIGINT NOT NULL REFERENCES gold.dim_customer (customer_key),
    customer_id TEXT NOT NULL,
    account_key BIGINT NOT NULL REFERENCES gold.dim_account (account_key),
    account_id TEXT NOT NULL,
    merchant_key BIGINT NOT NULL REFERENCES gold.dim_merchant (merchant_key),
    merchant_dim_id TEXT NOT NULL,
    merchant_id TEXT,
    merchant_category_key BIGINT REFERENCES gold.dim_merchant_category (merchant_category_key),
    merchant_category TEXT,
    city_key BIGINT REFERENCES gold.dim_city (city_key),
    city TEXT,
    channel_key BIGINT NOT NULL REFERENCES gold.dim_channel (channel_key),
    channel TEXT NOT NULL,
    transaction_status TEXT NOT NULL,
    currency TEXT NOT NULL,
    amount NUMERIC(18, 2) NOT NULL CHECK (amount >= 0),
    transaction_count SMALLINT NOT NULL DEFAULT 1 CHECK (transaction_count = 1),
    is_approved BOOLEAN NOT NULL,
    is_declined BOOLEAN NOT NULL,
    is_reversed BOOLEAN NOT NULL,
    is_fraud BOOLEAN NOT NULL,
    source_created_at TIMESTAMPTZ,
    arrival_delay_minutes DOUBLE PRECISION,
    quality_status TEXT NOT NULL CHECK (quality_status IN ('valid', 'warning')),
    quality_issue_codes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    quality_issue_count INTEGER NOT NULL DEFAULT 0 CHECK (quality_issue_count >= 0),
    duplicate_record_count INTEGER NOT NULL DEFAULT 1 CHECK (duplicate_record_count >= 1),
    _bronze_raw_record_hash TEXT NOT NULL,
    _silver_processed_at TIMESTAMPTZ NOT NULL,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_fact_transactions_event_date
    ON gold.fact_transactions (event_date);

CREATE INDEX IF NOT EXISTS ix_fact_transactions_customer_event_time
    ON gold.fact_transactions (customer_key, event_time);

CREATE INDEX IF NOT EXISTS ix_fact_transactions_account_event_time
    ON gold.fact_transactions (account_key, event_time);

CREATE INDEX IF NOT EXISTS ix_fact_transactions_merchant_event_time
    ON gold.fact_transactions (merchant_key, event_time);

CREATE TABLE IF NOT EXISTS gold.fact_transaction_quality_issue (
    transaction_id TEXT NOT NULL REFERENCES gold.fact_transactions (transaction_id) ON DELETE CASCADE,
    quality_issue_code TEXT NOT NULL REFERENCES gold.dim_quality_issue (quality_issue_code),
    issue_position INTEGER NOT NULL DEFAULT 1 CHECK (issue_position >= 1),
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (transaction_id, quality_issue_code, issue_position)
);

CREATE TABLE IF NOT EXISTS gold.fact_customer_daily (
    customer_key BIGINT NOT NULL REFERENCES gold.dim_customer (customer_key),
    customer_id TEXT NOT NULL,
    date_key INTEGER NOT NULL REFERENCES gold.dim_date (date_key),
    feature_date DATE NOT NULL,
    txn_count_1d BIGINT NOT NULL DEFAULT 0,
    approved_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    declined_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    reversed_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    amount_sum_1d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    amount_avg_1d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    amount_max_1d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    distinct_merchant_count_1d BIGINT NOT NULL DEFAULT 0,
    distinct_city_count_1d BIGINT NOT NULL DEFAULT 0,
    online_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    card_present_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    fraud_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    warning_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    late_arrival_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (customer_key, feature_date)
);

CREATE INDEX IF NOT EXISTS ix_fact_customer_daily_feature_date
    ON gold.fact_customer_daily (feature_date);

CREATE TABLE IF NOT EXISTS gold.fact_account_daily (
    account_key BIGINT NOT NULL REFERENCES gold.dim_account (account_key),
    account_id TEXT NOT NULL,
    customer_key BIGINT NOT NULL REFERENCES gold.dim_customer (customer_key),
    customer_id TEXT NOT NULL,
    date_key INTEGER NOT NULL REFERENCES gold.dim_date (date_key),
    feature_date DATE NOT NULL,
    txn_count_1d BIGINT NOT NULL DEFAULT 0,
    amount_sum_1d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    amount_max_1d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    distinct_merchant_count_1d BIGINT NOT NULL DEFAULT 0,
    distinct_city_count_1d BIGINT NOT NULL DEFAULT 0,
    declined_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    fraud_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (account_key, feature_date)
);

CREATE INDEX IF NOT EXISTS ix_fact_account_daily_feature_date
    ON gold.fact_account_daily (feature_date);

CREATE TABLE IF NOT EXISTS gold.fact_merchant_daily (
    merchant_key BIGINT NOT NULL REFERENCES gold.dim_merchant (merchant_key),
    merchant_dim_id TEXT NOT NULL,
    date_key INTEGER NOT NULL REFERENCES gold.dim_date (date_key),
    feature_date DATE NOT NULL,
    merchant_category TEXT,
    txn_count_1d BIGINT NOT NULL DEFAULT 0,
    amount_sum_1d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    amount_avg_1d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    distinct_customer_count_1d BIGINT NOT NULL DEFAULT 0,
    declined_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    fraud_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    fraud_rate_1d DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (fraud_rate_1d >= 0 AND fraud_rate_1d <= 1),
    warning_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (merchant_key, feature_date)
);

CREATE INDEX IF NOT EXISTS ix_fact_merchant_daily_feature_date
    ON gold.fact_merchant_daily (feature_date);

CREATE TABLE IF NOT EXISTS gold.fact_city_category_daily (
    city_key BIGINT REFERENCES gold.dim_city (city_key),
    merchant_category_key BIGINT REFERENCES gold.dim_merchant_category (merchant_category_key),
    city TEXT,
    merchant_category TEXT,
    date_key INTEGER NOT NULL REFERENCES gold.dim_date (date_key),
    feature_date DATE NOT NULL,
    txn_count_1d BIGINT NOT NULL DEFAULT 0,
    amount_sum_1d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    distinct_customer_count_1d BIGINT NOT NULL DEFAULT 0,
    distinct_merchant_count_1d BIGINT NOT NULL DEFAULT 0,
    fraud_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    fraud_rate_1d DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (fraud_rate_1d >= 0 AND fraud_rate_1d <= 1),
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (city_key, merchant_category_key, feature_date)
);

CREATE INDEX IF NOT EXISTS ix_fact_city_category_daily_feature_date
    ON gold.fact_city_category_daily (feature_date);

CREATE TABLE IF NOT EXISTS gold.fact_device_ip_daily (
    network_identifier TEXT NOT NULL,
    identifier_type TEXT NOT NULL CHECK (identifier_type IN ('device_id', 'ip_address')),
    date_key INTEGER NOT NULL REFERENCES gold.dim_date (date_key),
    feature_date DATE NOT NULL,
    txn_count_1d BIGINT NOT NULL DEFAULT 0,
    distinct_customer_count_1d BIGINT NOT NULL DEFAULT 0,
    distinct_account_count_1d BIGINT NOT NULL DEFAULT 0,
    distinct_merchant_count_1d BIGINT NOT NULL DEFAULT 0,
    fraud_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    warning_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (network_identifier, identifier_type, feature_date)
);

CREATE INDEX IF NOT EXISTS ix_fact_device_ip_daily_feature_date
    ON gold.fact_device_ip_daily (feature_date);

CREATE TABLE IF NOT EXISTS gold.feat_customer_rolling (
    customer_key BIGINT NOT NULL REFERENCES gold.dim_customer (customer_key),
    customer_id TEXT NOT NULL,
    event_timestamp TIMESTAMPTZ NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT now(),
    feature_date DATE NOT NULL,
    window_start_date DATE NOT NULL,
    window_end_date DATE NOT NULL,
    txn_count_7d BIGINT NOT NULL DEFAULT 0,
    txn_count_30d BIGINT NOT NULL DEFAULT 0,
    amount_sum_7d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    amount_sum_30d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    amount_avg_7d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    amount_avg_30d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    distinct_merchant_count_7d BIGINT NOT NULL DEFAULT 0,
    distinct_merchant_count_30d BIGINT NOT NULL DEFAULT 0,
    declined_txn_count_7d BIGINT NOT NULL DEFAULT 0,
    fraud_txn_count_30d BIGINT NOT NULL DEFAULT 0,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (customer_key, event_timestamp)
);

CREATE INDEX IF NOT EXISTS ix_feat_customer_rolling_feature_date
    ON gold.feat_customer_rolling (feature_date);

CREATE TABLE IF NOT EXISTS gold.feat_customer_total_orders_90d (
    customer_key BIGINT NOT NULL REFERENCES gold.dim_customer (customer_key),
    customer_id TEXT NOT NULL,
    event_timestamp TIMESTAMPTZ NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT now(),
    total_orders_90d BIGINT NOT NULL DEFAULT 0,
    feature_window_start_ts TIMESTAMPTZ NOT NULL,
    feature_window_end_ts TIMESTAMPTZ NOT NULL,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (customer_key, event_timestamp)
);

CREATE TABLE IF NOT EXISTS gold.feat_merchant_risk_rolling (
    merchant_key BIGINT NOT NULL REFERENCES gold.dim_merchant (merchant_key),
    merchant_dim_id TEXT NOT NULL,
    merchant_category TEXT,
    event_timestamp TIMESTAMPTZ NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT now(),
    feature_date DATE NOT NULL,
    window_start_date DATE NOT NULL,
    window_end_date DATE NOT NULL,
    baseline_window_start_date DATE NOT NULL,
    baseline_window_end_date DATE NOT NULL,
    merchant_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    merchant_txn_count_7d BIGINT NOT NULL DEFAULT 0,
    merchant_txn_count_30d BIGINT NOT NULL DEFAULT 0,
    merchant_txn_count_prior_30d BIGINT NOT NULL DEFAULT 0,
    merchant_amount_sum_1d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    merchant_amount_sum_7d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    merchant_amount_sum_30d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    merchant_amount_avg_30d NUMERIC(18, 2) NOT NULL DEFAULT 0,
    merchant_distinct_customer_count_1d BIGINT NOT NULL DEFAULT 0,
    merchant_declined_txn_count_1d BIGINT NOT NULL DEFAULT 0,
    merchant_fraud_rate_1d DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (merchant_fraud_rate_1d >= 0 AND merchant_fraud_rate_1d <= 1),
    merchant_fraud_txn_count_30d BIGINT NOT NULL DEFAULT 0,
    merchant_prior_fraud_rate_30d DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (merchant_prior_fraud_rate_30d >= 0 AND merchant_prior_fraud_rate_30d <= 1),
    merchant_burst_ratio_1d_to_prior_30d DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (merchant_burst_ratio_1d_to_prior_30d >= 0),
    merchant_category_txn_count_1d BIGINT,
    merchant_category_txn_count_30d BIGINT,
    merchant_category_amount_avg_30d NUMERIC(18, 2),
    merchant_category_prior_fraud_rate_30d DOUBLE PRECISION
        CHECK (
            merchant_category_prior_fraud_rate_30d IS NULL
            OR (
                merchant_category_prior_fraud_rate_30d >= 0
                AND merchant_category_prior_fraud_rate_30d <= 1
            )
        ),
    merchant_vs_category_amount_ratio_30d DOUBLE PRECISION
        CHECK (merchant_vs_category_amount_ratio_30d IS NULL OR merchant_vs_category_amount_ratio_30d >= 0),
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (merchant_key, event_timestamp)
);

CREATE INDEX IF NOT EXISTS ix_feat_merchant_risk_rolling_feature_date
    ON gold.feat_merchant_risk_rolling (feature_date);

CREATE INDEX IF NOT EXISTS ix_feat_merchant_risk_rolling_category_date
    ON gold.feat_merchant_risk_rolling (merchant_category, feature_date);

CREATE TABLE IF NOT EXISTS gold.feat_transaction_training (
    transaction_id TEXT PRIMARY KEY REFERENCES gold.fact_transactions (transaction_id) ON DELETE CASCADE,
    event_timestamp TIMESTAMPTZ NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT now(),
    customer_key BIGINT NOT NULL REFERENCES gold.dim_customer (customer_key),
    account_key BIGINT NOT NULL REFERENCES gold.dim_account (account_key),
    merchant_key BIGINT NOT NULL REFERENCES gold.dim_merchant (merchant_key),
    date_key INTEGER NOT NULL REFERENCES gold.dim_date (date_key),
    amount NUMERIC(18, 2) NOT NULL,
    channel TEXT NOT NULL,
    transaction_status TEXT NOT NULL,
    customer_txn_count_7d BIGINT,
    customer_amount_sum_30d NUMERIC(18, 2),
    customer_distinct_merchant_count_7d BIGINT,
    account_txn_count_1d BIGINT,
    account_amount_sum_1d NUMERIC(18, 2),
    merchant_feature_available BOOLEAN NOT NULL DEFAULT false,
    merchant_txn_count_1d BIGINT,
    merchant_txn_count_7d BIGINT,
    merchant_txn_count_30d BIGINT,
    merchant_fraud_rate_1d DOUBLE PRECISION,
    merchant_prior_fraud_rate_30d DOUBLE PRECISION,
    merchant_burst_ratio_1d_to_prior_30d DOUBLE PRECISION,
    merchant_category_txn_count_1d BIGINT,
    merchant_category_prior_fraud_rate_30d DOUBLE PRECISION,
    merchant_vs_category_amount_ratio_30d DOUBLE PRECISION,
    device_distinct_customer_count_1d BIGINT,
    ip_distinct_account_count_1d BIGINT,
    quality_issue_count INTEGER NOT NULL DEFAULT 0,
    duplicate_record_count INTEGER NOT NULL DEFAULT 1,
    arrival_delay_minutes DOUBLE PRECISION,
    is_fraud BOOLEAN NOT NULL,
    _gold_processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE gold.feat_transaction_training
    ADD COLUMN IF NOT EXISTS merchant_feature_available BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS merchant_txn_count_7d BIGINT,
    ADD COLUMN IF NOT EXISTS merchant_txn_count_30d BIGINT,
    ADD COLUMN IF NOT EXISTS merchant_prior_fraud_rate_30d DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS merchant_burst_ratio_1d_to_prior_30d DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS merchant_category_txn_count_1d BIGINT,
    ADD COLUMN IF NOT EXISTS merchant_category_prior_fraud_rate_30d DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS merchant_vs_category_amount_ratio_30d DOUBLE PRECISION;

CREATE OR REPLACE VIEW gold.obt_transaction_enriched AS
SELECT
    fact.transaction_id,
    fact.event_time,
    fact.event_date,
    fact.amount,
    fact.currency,
    fact.transaction_status,
    fact.is_approved,
    fact.is_declined,
    fact.is_reversed,
    fact.is_fraud,
    fact.customer_id,
    customer.primary_city AS customer_primary_city,
    customer.account_count AS customer_account_count,
    customer.fraud_rate AS customer_fraud_rate,
    fact.account_id,
    account.transaction_count AS account_transaction_count,
    account.lifetime_amount AS account_lifetime_amount,
    fact.merchant_id,
    merchant.merchant_category,
    merchant.primary_city AS merchant_primary_city,
    merchant.fraud_rate AS merchant_fraud_rate,
    fact.channel,
    channel.channel_group,
    channel.is_digital,
    channel.is_card_present,
    fact.quality_status,
    fact.quality_issue_count,
    fact.duplicate_record_count,
    fact._gold_processed_at
FROM gold.fact_transactions AS fact
JOIN gold.dim_customer AS customer
    ON fact.customer_key = customer.customer_key
JOIN gold.dim_account AS account
    ON fact.account_key = account.account_key
JOIN gold.dim_merchant AS merchant
    ON fact.merchant_key = merchant.merchant_key
JOIN gold.dim_channel AS channel
    ON fact.channel_key = channel.channel_key;

COMMENT ON TABLE bronze.raw_transactions IS 'Raw-preserved transaction records. Duplicates and raw format issues are allowed.';
COMMENT ON TABLE silver.stg_transactions IS 'Clean staged transactions with one selected row per transaction_id.';
COMMENT ON TABLE gold.fact_transactions IS 'Canonical Gold transaction fact table.';
COMMENT ON TABLE gold.dim_customer IS 'Customer SCD2 dimension with behavioral attributes.';
COMMENT ON TABLE gold.dim_merchant IS 'Merchant SCD2 dimension normalized by category and city.';
COMMENT ON TABLE gold.feat_merchant_risk_rolling IS 'Point-in-time merchant burst, historical fraud-rate, and category comparison features.';
COMMENT ON TABLE gold.feat_customer_total_orders_90d IS 'Example offline feature table with event_timestamp and created columns.';
COMMENT ON VIEW gold.obt_transaction_enriched IS 'Flattened transaction reporting view for DBeaver exploration.';
