fullnameOverride: kps
alertmanager:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    retention: 3d
    retentionSize: 2GB
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        memory: 1Gi
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
grafana:
  fullnameOverride: grafana
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  grafana.ini:
    server:
      root_url: https://grafana.fraudstream.localhost
    auth.anonymous:
      enabled: true
      org_role: Viewer
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: observability
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
